### ISSUE TITLE
Tera Auth Ticket

### ISSUE THREAD

**Issue by PatrickSantoZZ** [Kloct/tera-client#3]
is it possible that you make a EU Login Version? :3 its the only thing that needed to make this Client run on EU.

uwu~

**Comment by Kloct** [comment]
I actually just finished making my own variant of [tera-auth-ticket](https://github.com/Kloct/tera-auth-ticket) to fix some issues with NA logins but multi-region support is next on the list for that part of the project.
Will update here when I've made some progress 👍

**Comment by PatrickSantoZZ** [comment]
oh nice to hear this :)

**Comment by PatrickSantoZZ** [comment]
btw if you need how the EU Login works. i can give you my fiddler file + test account. i logged all the stuff. just write me in discord : NekOwO#0440

**Comment by Kloct** [comment]
For other people who are reading this If you want to run clientless on EU right now without using tera-auth-ticket. It is possible if hook the auth ticket from `C_LOGIN_ARBITER` on the EU game client. That ticket is one use so you'll have to reacquire it for every login session.

You'll also have to change the connection server and protocol/patch version to EU instead of NA.

Definitely a temporary solution but it seems like EU's doing quite a few things different in their launcher and it'll take some time to get a working tera-auth-ticket for that region.

**Comment by dozych** [comment]
> For other people who are reading this If you want to run clientless on EU right now without using tera-auth-ticket. It is possible if hook the auth ticket from `C_LOGIN_ARBITER` on the EU game client. That ticket is one use so you'll have to reacquire it for every login session.
> 
> You'll also have to change the connection server and protocol/patch version to EU instead of NA.
> 
> Definitely a temporary solution but it seems like EU's doing quite a few things different in their launcher and it'll take some time to get a working tera-auth-ticket for that region.

can u help with auth-ticket for other localization?

**Comment by Kloct** [comment]
Just added EU support https://github.com/Kloct/tera-client/commit/8bbbdc4d7a2eca18708d26b5c861575a35468f02
Closing this issue now
